development:
  adapter: postgresql
  encoding: unicode
  database: find_me_development
  host: localhost
  pool: 5
  username: postgres
  password: pancake

test:
  adapter: postgresql
  encoding: unicode
  database: find_me_test
  host: localhost
  pool: 5
  username: postgres
  password: pancake

production:
  adapter: postgresql
  encoding: unicode
  database: find_me_production
  host: localhost
  pool: 5
  username: postgres
  password: pancake
