development: &common
  adapter: postgresql
  encoding: unicode
  database: find_me_development
  host: localhost
  pool: 5
  username: adillera
  password: 123qwe

test:
  <<: *common
  database: find_me_test

production:
  <<: *common
  database: find_me_production
